name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          apktools=$(wget -O - https://dl-cdn.alpinelinux.org/alpine/edge/main/$(uname -m)/ | grep "apk-tools-static" | sed "s/^.*=\"//g;s/\".*//g") ;\
          REPO="http://dl-cdn.alpinelinux.org/alpine/edge" ;\
          wget -c "https://dl-cdn.alpinelinux.org/alpine/edge/main/$(uname -m)/$apktools" -O apk-tools-static.apk ;\
          tar -xf apk-tools-static.apk ;\
          sudo install sbin/apk.static /bin/apk ;\
          sudo chmod +x /bin/apk ;\
          sudo apk --arch $(uname -m) -X "${REPO}/main/" -U --allow-untrusted --root chroot --initdb add alpine-base bash;\
          echo "${REPO}/main/" | sudo tee chroot/etc/apk/repositories ;\
          echo "${REPO}/community/" | sudo tee -a chroot/etc/apk/repositories ;\
          echo "${REPO}/testing/" | sudo tee -a chroot/etc/apk/repositories ;\
          sudo chroot chroot apk update ;\
          sudo chroot chroot apk add proot-static ;\
          sudo tar --gz -cf alpine.tar.gz chroot/* ;\
          sudo mkdir /output ;\
          sudo mv alpine.tar.gz /output

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Auto build"
          files: |
            /output/*



